In [15]:
import numpy as np
import pandas as pd 

df = pd.read_csv("student_performance.csv")

df

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,1,18.5,95.6,3.8,97.9,A
1,2,14.0,80.0,2.5,83.9,B
2,3,19.5,86.3,5.3,100.0,A
3,4,25.7,70.2,7.0,100.0,A
4,5,13.4,81.9,6.9,92.0,A
...,...,...,...,...,...,...
999995,999996,18.0,95.5,4.8,100.0,A
999996,999997,15.7,82.7,6.7,88.3,A
999997,999998,14.2,85.1,5.8,87.9,A
999998,999999,25.3,90.0,5.3,100.0,A
999999,1000000,18.3,84.6,4.1,100.0,A

### How many rows and columns are there in the dataset?

In [16]:
# Return the dataset dimensions as (number of rows, number of columns).
df.shape

(1000000, 6)

### Show the first 10 rows of the dataset.

In [17]:
# Display the first 10 records to preview the dataset.
df.head(10)

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,1,18.5,95.6,3.8,97.9,A
1,2,14.0,80.0,2.5,83.9,B
2,3,19.5,86.3,5.3,100.0,A
3,4,25.7,70.2,7.0,100.0,A
4,5,13.4,81.9,6.9,92.0,A
5,6,13.4,65.1,5.0,97.5,A
6,7,26.1,81.8,5.9,100.0,A
7,8,20.4,100.0,4.0,96.1,A
8,9,11.7,100.0,8.2,69.8,C
9,10,18.8,67.6,6.0,80.3,B

### Show the last 10 rows of the dataset.

In [4]:
# Display the final 10 records to inspect the end of the dataset.
df.tail(10)

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
999990,999991,15.4,82.8,4.0,86.9,A
999991,999992,30.0,87.4,6.7,100.0,A
999992,999993,26.3,84.6,4.5,100.0,A
999993,999994,20.7,82.4,5.5,99.1,A
999994,999995,15.1,77.0,9.2,80.5,B
999995,999996,18.0,95.5,4.8,100.0,A
999996,999997,15.7,82.7,6.7,88.3,A
999997,999998,14.2,85.1,5.8,87.9,A
999998,999999,25.3,90.0,5.3,100.0,A
999999,1000000,18.3,84.6,4.1,100.0,A

### What are the column names in the dataset?

In [18]:
# List the dataset's column names.
df.columns

Index(['student_id', 'weekly_self_study_hours', 'attendance_percentage',
       'class_participation', 'total_score', 'grade'],
      dtype='object')

### What is the maximum value of weekly_self_study_hours?

In [19]:
# Find the largest number of weekly self-study hours in the dataset.
print(df["weekly_self_study_hours"].max())

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
209,210,40.0,68.1,6.7,100.0,A
2895,2896,40.0,75.7,4.2,100.0,A
15843,15844,40.0,99.5,8.0,100.0,A
18851,18852,40.0,91.7,7.0,100.0,A
20126,20127,40.0,94.1,3.0,100.0,A
...,...,...,...,...,...,...
971477,971478,40.0,74.2,7.7,100.0,A
973306,973307,40.0,90.0,6.2,100.0,A
974300,974301,40.0,78.8,2.5,100.0,A
976629,976630,40.0,93.9,7.0,100.0,A
980167,980168,40.0,82.6,7.2,100.0,A

### Which student studied the most hours in a week?

In [ ]:
# Select every student whose weekly study hours equal the dataset maximum.
df[df['weekly_self_study_hours'] == df['weekly_self_study_hours'].max()]

### Show the top 5 students by weekly_self_study_hours.

In [20]:
# Sort study hours from highest to lowest and display the top five students.
df.sort_values('weekly_self_study_hours' , ascending = False).head(5)

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
895979,895980,40.0,86.7,6.7,100.0,A
334965,334966,40.0,92.3,5.4,100.0,A
2895,2896,40.0,75.7,4.2,100.0,A
779223,779224,40.0,76.1,6.4,100.0,A
963524,963525,40.0,88.7,7.0,100.0,A

### Which student has the highest attendance percentage?

In [33]:
# Count records at the maximum attendance and calculate their share of all records.
std = df[df['attendance_percentage'] == df["attendance_percentage"].max()].count()['student_id']
total = df.shape[0]

per = (std * 100 / total)

print(f"percentage : {per}% ")

percentage : 6.7378%

### Which student has the highest class participation?

In [27]:
# Select every student whose class participation equals the dataset maximum.
df[df['class_participation'] == df['class_participation'].max()]

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
137,138,12.7,78.3,10.0,78.7,B
148,149,18.7,92.8,10.0,100.0,A
159,160,19.6,78.5,10.0,93.2,A
221,222,1.9,78.8,10.0,46.4,D
228,229,10.0,65.7,10.0,69.5,C
...,...,...,...,...,...,...
999764,999765,13.5,95.6,10.0,78.4,B
999771,999772,9.7,89.1,10.0,78.0,B
999774,999775,20.0,100.0,10.0,82.7,B
999859,999860,12.0,75.3,10.0,99.7,A
999909,999910,12.3,72.5,10.0,73.0,B

### Create a new column score_level 
"High" if total_score ≥ 90 , "Medium" if 70 ≤ total_score < 90, "Low" if total_score < 70

In [40]:
# Categorize each total score as High, Medium, or Low using the stated thresholds.
def score(x):
    if (x >= 90):
        return "High"
    elif(x >= 70 and x <= 90):
        return "Medium"
    elif(x < 70):
        return "Low"

In [41]:
# Apply the score categorization function to each student's total score.
df['score_level'] = df['total_score'].apply(score)

In [42]:
df

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade,score_level
0,1,18.5,95.6,3.8,97.9,A,High
1,2,14.0,80.0,2.5,83.9,B,Medium
2,3,19.5,86.3,5.3,100.0,A,High
3,4,25.7,70.2,7.0,100.0,A,High
4,5,13.4,81.9,6.9,92.0,A,High
...,...,...,...,...,...,...,...
999995,999996,18.0,95.5,4.8,100.0,A,High
999996,999997,15.7,82.7,6.7,88.3,A,Medium
999997,999998,14.2,85.1,5.8,87.9,A,Medium
999998,999999,25.3,90.0,5.3,100.0,A,High
999999,1000000,18.3,84.6,4.1,100.0,A,High

### Which student has the highest total_score?

In [43]:
# Select every student whose total score equals the dataset maximum.
df[df['total_score'] == df['total_score'].max()]

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade,score_level
2,3,19.5,86.3,5.3,100.0,A,High
3,4,25.7,70.2,7.0,100.0,A,High
6,7,26.1,81.8,5.9,100.0,A,High
17,18,17.2,74.0,8.1,100.0,A,High
20,21,25.3,89.3,6.4,100.0,A,High
...,...,...,...,...,...,...,...
999991,999992,30.0,87.4,6.7,100.0,A,High
999992,999993,26.3,84.6,4.5,100.0,A,High
999995,999996,18.0,95.5,4.8,100.0,A,High
999998,999999,25.3,90.0,5.3,100.0,A,High
999999,1000000,18.3,84.6,4.1,100.0,A,High

### How many students scored exactly 100 in total_score?

In [50]:
# Count the students whose total score is exactly 100.
(df['total_score'] == 100).sum()

268121

### Make a new column for study efficiency = total_score ÷ weekly_self_study_hours.

In [57]:
# Calculate score per weekly study hour and round the efficiency to two decimals.
df['study_efficiency'] = (df['total_score'] / df['weekly_self_study_hours']).round(2)

df

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade,score_level,study_efficiency
0,1,18.5,95.6,3.8,97.9,A,High,5.29
1,2,14.0,80.0,2.5,83.9,B,Medium,5.99
2,3,19.5,86.3,5.3,100.0,A,High,5.13
3,4,25.7,70.2,7.0,100.0,A,High,3.89
4,5,13.4,81.9,6.9,92.0,A,High,6.87
...,...,...,...,...,...,...,...,...
999995,999996,18.0,95.5,4.8,100.0,A,High,5.56
999996,999997,15.7,82.7,6.7,88.3,A,Medium,5.62
999997,999998,14.2,85.1,5.8,87.9,A,Medium,6.19
999998,999999,25.3,90.0,5.3,100.0,A,High,3.95
999999,1000000,18.3,84.6,4.1,100.0,A,High,5.46

### Create a new column study_category
"Light" if weekly_self_study_hours < 10, 
"Moderate" if 10 ≤ hours ≤ 20, 
"Heavy" if hours > 20

In [58]:
# Categorize weekly study hours as Light, Moderate, or Heavy using the stated ranges.
def category(a):
    if a < 10:
        return "Light"
    elif a >= 10 and a <=20:
        return "Moderate"
    elif a > 20 :
        return "Heavy"

In [59]:
# Apply the study-hour categorization function to every student.
df['study_category'] = df['weekly_self_study_hours'].apply(category)

In [60]:
df

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade,score_level,study_efficiency,study_category
0,1,18.5,95.6,3.8,97.9,A,High,5.29,Moderate
1,2,14.0,80.0,2.5,83.9,B,Medium,5.99,Moderate
2,3,19.5,86.3,5.3,100.0,A,High,5.13,Moderate
3,4,25.7,70.2,7.0,100.0,A,High,3.89,Heavy
4,5,13.4,81.9,6.9,92.0,A,High,6.87,Moderate
...,...,...,...,...,...,...,...,...,...
999995,999996,18.0,95.5,4.8,100.0,A,High,5.56,Moderate
999996,999997,15.7,82.7,6.7,88.3,A,Medium,5.62,Moderate
999997,999998,14.2,85.1,5.8,87.9,A,Medium,6.19,Moderate
999998,999999,25.3,90.0,5.3,100.0,A,High,3.95,Heavy
999999,1000000,18.3,84.6,4.1,100.0,A,High,5.46,Moderate