# 🐼 Pandas - Class 11: Advanced Tricks & Performance
Welcome to **Class 11** of our Pandas series. Today we’ll explore advanced techniques to write efficient, clean, and optimized Pandas code.

## 1. Applying Custom Functions with `apply()` / `map()`
- `apply()` lets you apply a custom function across rows or columns.
- `map()` is for applying functions element-wise to a Series.
- Both are handy for transformations, calculations, and cleaning data.

In [3]:
import pandas as pd

data = {
    "Name": ["rahul kumar", "PRIYA SHARMA", "amit singh", "NEHA GUPTA", "rohan das", "ANJALI KUMARI"],
    "Age": [22, 24, 21, 25, 23, 26],
    "Maths": [85, 67, 92, 45, 78, 59],
    "Computer": [85, 67, 92, 45, 78, 59],
    "Salary": [25000, 32000, 28000, 40000, 30000, 35000],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "IT"]
}

df = pd.DataFrame(data)

df

            Name  Age  Maths  Computer  Salary Department
0    rahul kumar   22     85        85   25000         IT
1   PRIYA SHARMA   24     67        67   32000         HR
2     amit singh   21     92        92   28000         IT
3     NEHA GUPTA   25     45        45   40000    Finance
4      rohan das   23     78        78   30000         HR
5  ANJALI KUMARI   26     59        59   35000         IT

In [5]:
#Convert all names to uppercase:

df['Name'] = df['Name'].map(str.upper) 

df

            Name  Age  Maths  Computer  Salary Department  Comp
0    RAHUL KUMAR   22     85        85   25000         IT    85
1   PRIYA SHARMA   24     67        67   32000         HR    78
2     AMIT SINGH   21     92        92   28000         IT    56
3     NEHA GUPTA   25     45        45   40000    Finance    78
4      ROHAN DAS   23     78        78   30000         HR    96
5  ANJALI KUMARI   26     59        59   35000         IT   100

In [4]:
df['Comp'] = [85,78,56,78,96,100]

In [11]:
# df['Total_Marks'] = df[['Maths','Computer']].apply(
#     lambda row: row.sum() , axis=1
# )

df['Total_MRKS'] = df['Maths'] + df['Computer']

df

,Name,Age,Maths,Computer,Salary,Department,Comp,Total_Marks,Total_MRKS
0,RAHUL KUMAR,22,85,85,25000,IT,85,170,170
1,PRIYA SHARMA,24,67,67,32000,HR,78,134,134
2,AMIT SINGH,21,92,92,28000,IT,56,184,184
3,NEHA GUPTA,25,45,45,40000,Finance,78,90,90
4,ROHAN DAS,23,78,78,30000,HR,96,156,156
5,ANJALI KUMARI,26,59,59,35000,IT,100,118,118

In [14]:
col_mean = df[['Maths','Computer']].apply(
    lambda col : col.mean()
)

df

print(col_mean)

Maths       71.0
Computer    71.0
dtype: float64

In [23]:
def to_grade(s):
    if s>=90:
        return 'A'
    elif s>=80:
        return "B"
    elif s>=70:
        return 'C'
    else:
        return "Fail"


df['M_GRADE'] = df['Maths'].apply(to_grade)

df

,Name,Age,Maths,Computer,Salary,Department,Comp,Total_Marks,Total_MRKS,MEAN,M_GRADE
0,RAHUL KUMAR,22,85,85,25000,IT,85,170,170,NaN,B
1,PRIYA SHARMA,24,67,67,32000,HR,78,134,134,NaN,Fail
2,AMIT SINGH,21,92,92,28000,IT,56,184,184,NaN,A
3,NEHA GUPTA,25,45,45,40000,Finance,78,90,90,NaN,Fail
4,ROHAN DAS,23,78,78,30000,HR,96,156,156,NaN,C
5,ANJALI KUMARI,26,59,59,35000,IT,100,118,118,NaN,Fail

In [24]:
df = df.drop('MEAN',axis = 1)

In [25]:
df

,Name,Age,Maths,Computer,Salary,Department,Comp,Total_Marks,Total_MRKS,M_GRADE
0,RAHUL KUMAR,22,85,85,25000,IT,85,170,170,B
1,PRIYA SHARMA,24,67,67,32000,HR,78,134,134,Fail
2,AMIT SINGH,21,92,92,28000,IT,56,184,184,A
3,NEHA GUPTA,25,45,45,40000,Finance,78,90,90,Fail
4,ROHAN DAS,23,78,78,30000,HR,96,156,156,C
5,ANJALI KUMARI,26,59,59,35000,IT,100,118,118,Fail

In [27]:
df['Name'] = df['Name'].map(str.lower)

df

,Name,Age,Maths,Computer,Salary,Department,Comp,Total_Marks,Total_MRKS,M_GRADE
0,rahul kumar,22,85,85,25000,IT,85,170,170,B
1,priya sharma,24,67,67,32000,HR,78,134,134,Fail
2,amit singh,21,92,92,28000,IT,56,184,184,A
3,neha gupta,25,45,45,40000,Finance,78,90,90,Fail
4,rohan das,23,78,78,30000,HR,96,156,156,C
5,anjali kumari,26,59,59,35000,IT,100,118,118,Fail

In [29]:
df['Maths_extras'] = df['Maths'].map(lambda x : x+5)

df

,Name,Age,Maths,Computer,Salary,Department,Comp,Total_Marks,Total_MRKS,M_GRADE,Maths_extras
0,rahul kumar,22,85,85,25000,IT,85,170,170,B,90
1,priya sharma,24,67,67,32000,HR,78,134,134,Fail,72
2,amit singh,21,92,92,28000,IT,56,184,184,A,97
3,neha gupta,25,45,45,40000,Finance,78,90,90,Fail,50
4,rohan das,23,78,78,30000,HR,96,156,156,C,83
5,anjali kumari,26,59,59,35000,IT,100,118,118,Fail,64