# 🐼 Pandas - Class 3: Data Cleaning Essentials
Welcome to **Class 3** of our Pandas series. Today we’ll learn how to clean and prepare data for analysis.

## Handling Missing Values
Real-world datasets often have missing data. Pandas offers:
- `isna()` / `isnull()` → detect missing values (returns True/False)
- `dropna()` → remove missing values (rows/columns)
- `fillna()` → replace missing values with a given value or method (e.g., forward fill)

Always inspect how much data is missing before deciding to drop or fill.

In [218]:
import pandas as pd
import numpy as np
a = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, None, 35, 40, None],
    "City": ["Delhi", "Mumbai", None, "Bangalore", "Chennai"],
    "Score": [85, 91, np.nan, 88, 95]
}
b = pd.DataFrame(a)

b

      Name   Age       City  Score
0    Alice  25.0      Delhi   85.0
1      Bob   NaN     Mumbai   91.0
2  Charlie  35.0       None    NaN
3    David  40.0  Bangalore   88.0
4     Emma   NaN    Chennai   95.0

In [219]:
b.isnull()

    Name    Age   City  Score
0  False  False  False  False
1  False   True  False  False
2  False  False   True   True
3  False  False  False  False
4  False   True  False  False

In [220]:
b.isna().sum()

Name     0
Age      2
City     1
Score    1
dtype: int64

In [221]:
x = b.dropna()
x

    Name   Age       City  Score
0  Alice  25.0      Delhi   85.0
3  David  40.0  Bangalore   88.0

In [222]:
b['Age'] = b['Age'].fillna(round(b['Age'].mean()))
b

      Name   Age       City  Score
0    Alice  25.0      Delhi   85.0
1      Bob  33.0     Mumbai   91.0
2  Charlie  35.0       None    NaN
3    David  40.0  Bangalore   88.0
4     Emma  33.0    Chennai   95.0

In [223]:
b['Age'] = b['Age'].fillna(round(b['Age'].mean()))
b['City'] = b['City'].fillna(b['City'].mode())
b['Score'] = b['Score'].fillna(b['Score'].mean())
b

      Name   Age       City  Score
0    Alice  25.0      Delhi  85.00
1      Bob  33.0     Mumbai  91.00
2  Charlie  35.0      Delhi  89.75
3    David  40.0  Bangalore  88.00
4     Emma  33.0    Chennai  95.00

In [224]:
b.isna().sum()

Name     0
Age      0
City     0
Score    0
dtype: int64

In [225]:
b

      Name   Age       City  Score
0    Alice  25.0      Delhi  85.00
1      Bob  33.0     Mumbai  91.00
2  Charlie  35.0      Delhi  89.75
3    David  40.0  Bangalore  88.00
4     Emma  33.0    Chennai  95.00

In [226]:
b['Name'] = b['Name'].replace("bob","shivam")
b

      Name   Age       City  Score
0    Alice  25.0      Delhi  85.00
1      Bob  33.0     Mumbai  91.00
2  Charlie  35.0      Delhi  89.75
3    David  40.0  Bangalore  88.00
4     Emma  33.0    Chennai  95.00

## Changing Data Types (`astype`)
- Convert a column to a different type using `astype()`.
- Examples: converting strings to numbers, integers to floats, or columns to category.

Be careful: make sure the data is compatible with the new type!

In [227]:
a = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 35, 40, 22],
    "Score": [88, 92, 79, 85, 95]
}

b = pd.DataFrame(a)

In [228]:
b['Age']=b['Age'].astype(int)
b

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

## Replacing Values (`replace`)
- Use `replace()` to substitute specific values or patterns.
- Useful for cleaning labels, fixing typos, or mapping categories.

In [229]:
data = {
    "City": ["Bhopal", "Indore", "Bhopal", "Ujjain"]
}

df = pd.DataFrame(data)
# Replace "Bhopal" with "Sehore"
df["City"] = df["City"].replace("Bhopal", "Sehore")

print(df)

     City
0  Sehore
1  Indore
2  Sehore
3  Ujjain

In [230]:
b['Name'] = b['Name'].replace("Bob","Shivam")
b

      Name  Age  Score
0    Alice   25     88
1   Shivam   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

In [231]:
b['Score'] = b['Score'].replace({88:90,79:97})
b

      Name  Age  Score
0    Alice   25     90
1   Shivam   30     92
2  Charlie   35     97
3    David   40     85
4     Emma   22     95

## Dropping Rows & Columns (`drop`)
- `drop(labels, axis=0)` → drop rows by index labels.
- `drop(labels, axis=1)` → drop columns by name.
- Use `inplace=True` if you want to modify the DataFrame directly.

In [232]:
# Drop a row
import pandas as pd

df = pd.DataFrame({
    "Name": ["Aman", "Riya", "Vikas"],
    "Age": [20, 21, 22]
})

# Row with index 1 remove
df = df.drop(1)

print(df)

    Name  Age
0   Aman   20
2  Vikas   22

In [233]:
# Drop a column
df = pd.DataFrame({
    "Name": ["Aman", "Riya", "Vikas"],
    "Age": [20, 21, 22]
})
# Age column remove
df = df.drop("Age", axis=1)

print(df)

    Name
0   Aman
1   Riya
2  Vikas

In [234]:
# Modify dataframe
df = pd.DataFrame({
    "Name": ["Aman", "Riya", "Vikas"],
    "Age": [20, 21, 22]
})

# Directly modify DataFrame
df.drop("Age", axis=1, inplace=True)

print(df)

    Name
0   Aman
1   Riya
2  Vikas

In [235]:
b.drop([0,2],axis=0)

     Name  Age  Score
1  Shivam   30     92
3   David   40     85
4    Emma   22     95

In [265]:
b.drop(['Age'],axis=1,inplace = True)

In [239]:
c = b 
c
# We should always keep our original data safe

      Name  Age  Score
0    Alice   25     90
1   Shivam   30     92
2  Charlie   35     97
3    David   40     85
4     Emma   22     95

## Detecting & Removing Duplicates
- `duplicated()` → returns a Boolean Series marking duplicate rows.
- `drop_duplicates()` → remove duplicate rows.
- You can specify `subset` (columns) and `keep` ('first', 'last', or False).

In [ ]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "Alice", "Bob", "David"],
    "Age": [25, 30, 35, 25, 30, 40],
    "Score": [88, 92, 79, 88, 92, 85]
}

df = pd.DataFrame(data)

In [ ]:
df.duplicated()

## Mini Practice
1. Create a messy DataFrame with missing values, wrong data types, typos, extra columns, and duplicates.
2. Clean it step-by-step using what you learned:
   - Handle missing values
   - Change data types
   - Replace incorrect values
   - Drop unnecessary rows/columns
   - Remove duplicates

In [244]:
import pandas as pd
import numpy as np

# 1. Create a messy DataFrame
data = {
    "Name": ["Alice", "Bob", "Chrlie", "David", "Alice", None],
    "Age": ["25", "30", None, "40", "25", "30"],      # ages stored as strings, with missing value
    "City": ["Delhi", "Mumbai", "Pun", "Bangalore", "Delhi", "Mumbai"],  # typo: "Pun" -> "Pune"
    "Score": [85, None, 78, 88, 85, 91],              # missing value in Score
    "Extra": ["x", "y", "z", "x", "y", "z"]           # extra column we don't really need
}

df = pd.DataFrame(data)

print("Original messy DataFrame:")
print(df)

# 2. Handle missing values
# Fill or drop as needed

# 3. Change data types
# Convert Age to int, Score to float, etc.

# 4. Replace incorrect values
# Fix 'Pun' -> 'Pune', maybe unify Name spellings if needed

# 5. Drop unnecessary rows/columns
# Remove 'Extra' or any row you don't want

# 6. Remove duplicates
# Use duplicated() and drop_duplicates()

# 7. Final clean DataFrame
# Print the cleaned DataFrame and check info()

Original messy DataFrame:
     Name   Age       City  Score Extra
0   Alice    25      Delhi   85.0     x
1     Bob    30     Mumbai    NaN     y
2  Chrlie  None        Pun   78.0     z
3   David    40  Bangalore   88.0     x
4   Alice    25      Delhi   85.0     y
5    None    30     Mumbai   91.0     z

---
## Summary
- Learned to handle missing values (`isna`, `dropna`, `fillna`).
- Converted column data types with `astype`.
- Cleaned up incorrect entries with `replace`.
- Removed unwanted rows/columns with `drop`.
- Detected and removed duplicates.

In [245]:
df

     Name   Age       City  Score Extra
0   Alice    25      Delhi   85.0     x
1     Bob    30     Mumbai    NaN     y
2  Chrlie  None        Pun   78.0     z
3   David    40  Bangalore   88.0     x
4   Alice    25      Delhi   85.0     y
5    None    30     Mumbai   91.0     z

In [250]:

type(df)

pandas.core.frame.DataFrame

In [253]:
# 2. Handle missing values
# Fill or drop as needed
temp = df.copy()
temp.drop(['Extra'],axis = 1,inplace = True)
temp

     Name   Age       City  Score
0   Alice    25      Delhi   85.0
1     Bob    30     Mumbai    NaN
2  Chrlie  None        Pun   78.0
3   David    40  Bangalore   88.0
4   Alice    25      Delhi   85.0
5    None    30     Mumbai   91.0

In [254]:
temp.duplicated()

0    False
1    False
2    False
3    False
4     True
5    False
dtype: bool

In [255]:
temp.drop_duplicates()

     Name   Age       City  Score
0   Alice    25      Delhi   85.0
1     Bob    30     Mumbai    NaN
2  Chrlie  None        Pun   78.0
3   David    40  Bangalore   88.0
5    None    30     Mumbai   91.0

In [267]:
# 3. Change data types
# Convert Age to int, Score to float, etc.

# Convert Age to integer
temp['Age'] = temp['Age'].astype(int)

# Replace null Age with mean
temp['Age'] = temp['Age'].fillna(temp['Age'].mean())



# Replace null Score with mode
temp['Score'] = temp['Score'].fillna(temp['Score'].mode()[0])

# Convert Score to float
temp['Score'] = temp['Score'].astype(float)

print("This is the result")
temp

This is the result

     Name  Age       City  Score
0   Alice   25      Delhi   85.0
1     Bob   30     Mumbai   85.0
2  Chrlie   30       Pune   78.0
3   David   40  Bangalore   88.0
4   Alice   25      Delhi   85.0
5    None   30     Mumbai   91.0

In [257]:
# 4. Replace incorrect values
# Fix 'Pun' -> 'Pune', maybe unify Name spellings if needed

temp['City'] = temp['City'].replace('Pun','Pune')
temp

     Name  Age       City  Score
0   Alice   25      Delhi   85.0
1     Bob   30     Mumbai   85.0
2  Chrlie   30       Pune   78.0
3   David   40  Bangalore   88.0
4   Alice   25      Delhi   85.0
5    None   30     Mumbai   91.0

In [259]:
# 6. Remove duplicates
# Use duplicated() and drop_duplicates()

temp.duplicated()
temp.drop_duplicates()
temp.dropna()

     Name  Age       City  Score
0   Alice   25      Delhi   85.0
1     Bob   30     Mumbai   85.0
2  Chrlie   30       Pune   78.0
3   David   40  Bangalore   88.0
4   Alice   25      Delhi   85.0

In [262]:
# 7. Final clean DataFrame
# Print the cleaned DataFrame and check info()

temp

     Name  Age       City  Score
0   Alice   25      Delhi   85.0
1     Bob   30     Mumbai   85.0
2  Chrlie   30       Pune   78.0
3   David   40  Bangalore   88.0
4   Alice   25      Delhi   85.0
5    None   30     Mumbai   91.0

In [264]:
temp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     6 non-null      int32
 2   City    6 non-null      object
 3   Score   6 non-null      float64
dtypes: float64(1), int32(1), object(2)
memory usage: 300.0+ bytes