# 🐼 Pandas - Class 11: Advanced Tricks & Performance
Welcome to **Class 11** of our Pandas series. Today we’ll explore advanced techniques to write efficient, clean, and optimized Pandas code.

## 1. Applying Custom Functions with `apply()` / `map()`
- `apply()` lets you apply a custom function across rows or columns.
- `map()` is for applying functions element-wise to a Series.
- Both are handy for transformations, calculations, and cleaning data.

In [6]:
import pandas as pd

data = {
    "Name": ["rahul kumar", "PRIYA SHARMA", "amit singh", "NEHA GUPTA", "rohan das", "ANJALI KUMARI"],
    "Age": [22, 24, 21, 25, 23, 26],
    "Maths": [85, 67, 92, 45, 78, 59],
    "Computer": [85, 67, 92, 45, 78, 59],
    "Salary": [25000, 32000, 28000, 40000, 30000, 35000],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "IT"]
}

df = pd.DataFrame(data)

df

            Name  Age  Maths  Computer  Salary Department
0    rahul kumar   22     85        85   25000         IT
1   PRIYA SHARMA   24     67        67   32000         HR
2     amit singh   21     92        92   28000         IT
3     NEHA GUPTA   25     45        45   40000    Finance
4      rohan das   23     78        78   30000         HR
5  ANJALI KUMARI   26     59        59   35000         IT

In [7]:
#Convert all names to uppercase:

df['Name'] = df['Name'].map(str.upper) 

df

            Name  Age  Maths  Computer  Salary Department
0    RAHUL KUMAR   22     85        85   25000         IT
1   PRIYA SHARMA   24     67        67   32000         HR
2     AMIT SINGH   21     92        92   28000         IT
3     NEHA GUPTA   25     45        45   40000    Finance
4      ROHAN DAS   23     78        78   30000         HR
5  ANJALI KUMARI   26     59        59   35000         IT