# 🐼 Pandas - Class 4: Data Selection & Filtering
Welcome to **Class 4** of our Pandas series. Today we’ll explore techniques to select and filter data in a DataFrame.

## 1. Boolean Indexing & Conditional Selection
- Use comparison operators to build conditions (e.g., `df['col'] > 50`).
- Pass the condition inside `df[...]` to get matching rows.
- Combine multiple conditions with `&` (AND), `|` (OR), and `~` (NOT).
- Parentheses are required when combining conditions.

In [33]:
import numpy as np
import pandas as pd

# Create a dictionary
data = {
    "Name": ["Rahul", "Aman", "Priya", "Sneha", "Vikash"],
    "Age": [20, 21, 35, 22, 40],
    "Score": [85, 78, 92, 88, 76]
}

# Convert dictionary into DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
df

     Name  Age  Score
0   Rahul   20     85
1    Aman   21     78
2   Priya   35     92
3   Sneha   22     88
4  Vikash   40     76

In [34]:
temp = df.copy()
temp

     Name  Age  Score
0   Rahul   20     85
1    Aman   21     78
2   Priya   35     92
3   Sneha   22     88
4  Vikash   40     76

In [35]:
temp[temp['Age']>20]     # comparison operator to satisfy condition

     Name  Age  Score
1    Aman   21     78
2   Priya   35     92
3   Sneha   22     88
4  Vikash   40     76

In [36]:
temp[(temp['Age']>25)|(temp['Score']<75)]

     Name  Age  Score
2   Priya   35     92
4  Vikash   40     76

In [37]:
temp[~(temp['Age']>30)]

    Name  Age  Score
0  Rahul   20     85
1   Aman   21     78
3  Sneha   22     88

## 2. Filtering Rows with Multiple Conditions
- Combine two or more conditions to refine selection.
- Remember to enclose each condition in parentheses.

In [38]:
temp[(temp['Age']>20) & (temp['Score']>70)]

     Name  Age  Score
1    Aman   21     78
2   Priya   35     92
3   Sneha   22     88
4  Vikash   40     76

## 3. Using `query()` for Cleaner Filtering
- `query()` allows filtering rows with a string expression.
- It's concise and readable for complex conditions.
- Variables can be passed using the `@` symbol.

In [39]:
temp.query("Age>21")

     Name  Age  Score
2   Priya   35     92
3   Sneha   22     88
4  Vikash   40     76

In [40]:
temp.query("Age>20 and Score>80")

    Name  Age  Score
2  Priya   35     92
3  Sneha   22     88

In [41]:
value = 85
temp.query('Score>@value')

    Name  Age  Score
2  Priya   35     92
3  Sneha   22     88

## 4. String Operations on Columns
- Use the `.str` accessor for vectorized string methods.
- Common methods: `contains`, `replace`, `startswith`, `endswith`, `lower`, `upper`.
- Useful for cleaning or filtering text data.

In [50]:
temp['Name'].str.upper()

KeyError: "None of [Index(['RAHUL', 'AMAN', 'PRIYA', 'SNEHA', 'VIKASH'], dtype='object')] are in the [columns]"

In [49]:
temp[temp['Name'].str.contains('i')]

     Name  Age  Score
2   Priya   35     92
4  Vikash   40     76

In [60]:
temp.dtypes()

AttributeError: 'list' object has no attribute 'dtypes'

In [57]:
temp['Name'] = temp['Name'].str.replace('Priya','Prakriti')
temp

TypeError: list indices must be integers or slices, not str

## Mini Practice
1. Build a DataFrame with columns such as Name, Age, City, Score.
2. Use boolean indexing to select rows where Age > 25.
3. Filter rows where City is either 'Delhi' or 'Mumbai'.
4. Use query() to find rows with Score >= 85 and Age < 35.
5. Clean a text column using str.replace or str.lower.

In [46]:
df

     Name  Age  Score
0   Rahul   20     85
1    Aman   21     78
2   Priya   35     92
3   Sneha   22     88
4  Vikash   40     76

In [43]:


# 1. Build a DataFrame with columns: Name, Age, City, Score


# 2. Use boolean indexing to select rows where Age > 25
# Write your code here

# 3. Filter rows where City is either 'Delhi' or 'Mumbai'
# Write your code here

# 4. Use query() to find rows with Score >= 85 and Age < 35
# Write your code here

# 5. Clean a text column using str.replace or str.lower
# Example: convert City names to lowercase or replace "delhi" with "New Delhi"
# Write your code here

---
## Summary
- Learned to use boolean indexing and conditional selection.
- Filtered rows with multiple conditions.
- Used `query()` for clean filtering.
- Applied string operations with the `.str` accessor.