# 🐼 Pandas - Class 2: DataFrame Basics
Welcome to **Class 2**. Today we’ll learn how to **inspect**, **select**, and **organize** data inside a DataFrame.

## 1 Inspecting Data
Quick ways to understand your dataset:
- `head(n)` → first *n* rows (default 5)
- `tail(n)` → last *n* rows
- `info()` → columns, non-null counts, and dtypes
- `shape` → (rows, columns)
- `dtypes` → data type of each column

In [24]:
import pandas as pd

# Create a small DataFrame
a = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 35, 40, 22],
    "Score": [88, 92, 79, 85, 95]
}

b = pd.DataFrame(a)

b.head(2)
b.info()
b.shape
b.dtypes
b

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   Score   5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

## 2 Selecting Columns & Rows
Ways to access parts of a DataFrame:
- Single column → `df['col']`
- Multiple columns → `df[['col1','col2']]`
- Label-based selection → `df.loc[row_label, col_label]`
- Integer-index selection → `df.iloc[row_idx, col_idx]`
Tip: `:` means "all rows/columns" in that dimension.

In [23]:
b['Name'] # single column
b[['Name','Score']] #multiple column , fancy indexing
type(b.loc[0])
b.loc[1:3,["Name","Score"]]

      Name  Score
1      Bob     92
2  Charlie     79
3    David     85

## 3 Index & Columns Overview
- `df.index` → row labels
- `df.columns` → column names
- `df.values` → underlying NumPy array (read-only; prefer using DataFrame ops)

In [32]:
b.index
b.columns
b.values

array([['Alice', 25, 88],
       ['Bob', 30, 92],
       ['Charlie', 35, 79],
       ['David', 40, 85],
       ['Emma', 22, 95]], dtype=object)

## 4 Renaming Columns & Setting an Index
- Rename columns → `df.rename(columns={'old':'new'}, inplace=False)`
- Set a column as index → `df.set_index('column_name', inplace=False)`
- Reset index → `df.reset_index(inplace=False)`
 If you don't use `inplace=True`, remember to assign the result back to a variable.

In [46]:

c = b.rename(columns={'Name':'S_Name'},inplace=False)

i = b.set_index('Age',inplace = False)
i

i = b.reset_index(inplace=False)
i

   index     Name  Age  Score
0      0    Alice   25     88
1      1      Bob   30     92
2      2  Charlie   35     79
3      3    David   40     85
4      4     Emma   22     95

## 5 Basic Attributes Recap
- `df.columns` → names of all columns
- `df.index` → row labels
- `df.values` → NumPy array (data only)
These are handy for quick checks and loops (though vectorized ops are preferred).

## Mini Practice
1. Create a DataFrame with at least 5 rows and 4 columns (mix of numeric + text).
2. Show the first 3 rows, last 2 rows, and the info.
3. Select a sub-DataFrame with only 2 columns.
4. Rename one column and set any column as index, then reset it back.
5. Print `df.shape`, `df.dtypes`, and `df.columns`.

In [2]:
import pandas as pd

# Create a DataFrame with at least 5 rows & 4 columns (mix of numbers + text)
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 35, 40, 22],
    "City": ["Delhi", "Mumbai", "Pune", "Bangalore", "Chennai"],
    "Score": [85, 91, 78, 88, 95]
}

df = pd.DataFrame(data)

# Show the first 3 rows, last 2 rows, and info
# your code here

# Select a sub-DataFrame with only 2 columns
# your code here

# Rename one column and set any column as index, then reset it back
# your code here

# Print df.shape, df.dtypes, and df.columns
# your code here

---
## ✅ Summary
- You learned to **inspect** a DataFrame (`head`, `tail`, `info`, `shape`, `dtypes`).
- You practiced **selecting** columns/rows using `[]`, `.loc`, and `.iloc`.
- You explored **index/columns** and basic attributes.
- You **renamed** columns and **set/reset** an index.

Next up: **Data Cleaning Essentials** (missing values, types, duplicates).

In [23]:
# Show the first 3 rows, last 2 rows, and info
# your code here
temp =df.copy()
temp

result = pd.concat([temp.head(3), temp.tail(2)])
result.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   City    5 non-null      object
 3   Score   5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [25]:
# Select a sub-DataFrame with only 2 columns
# your code here
temp[['Name','Age']]

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40
4     Emma   22

In [31]:
# Rename one column and set any column as index, then reset it back
# your code here

temp.rename(columns={'Name':'E_NAME'})
temp.set_index('Age')
temp.reset_index()

   index     Name  Age       City  Score
0      0    Alice   25      Delhi     85
1      1      Bob   30     Mumbai     91
2      2  Charlie   35       Pune     78
3      3    David   40  Bangalore     88
4      4     Emma   22    Chennai     95

In [35]:
# Print df.shape, df.dtypes, and df.columns
# your code here
temp.shape
temp.dtypes
df.columns

Index(['Name', 'Age', 'City', 'Score'], dtype='object')