# 🐼 Pandas - Class 7: Merging, Joining & Concatenation
Welcome to **Class 7** of our Pandas series. Today we’ll learn how to combine multiple DataFrames using different techniques.

## 1. Using `concat()` for Stacking Data
- `pd.concat()` combines DataFrames vertically (rows) or horizontally (columns).
- Use `axis=0` for vertical stacking (default), `axis=1` for horizontal.
- `ignore_index=True` can reset the index after concatenation.

In [18]:
import pandas as pd

# Dataset 1: Product details
df1 = pd.DataFrame({
    "Product": ["Laptop", "Mouse", "Keyboard", "Monitor"],
    "Price": [55000, 800, 1500, 12000],
    "Stock": [10, 50, 30, 15],
    "Rating": [4.5, 4.2, 4.4, 4.6]
})

# Dataset 2: More products
# Same columns as df1 → good for vertical stacking
df2 = pd.DataFrame({
    "Product": ["Headphones", "Webcam", "Printer", "Speaker"],
    "Price": [2500, 3500, 8500, 3000],
    "Stock": [25, 18, 8, 20],
    "Rating": [4.3, 4.1, 4.0, 4.4]
})

# Dataset 3: Additional information
# Different columns → good for horizontal stacking
df3 = pd.DataFrame({
    "Category": ["Electronics", "Accessories", "Accessories", "Electronics"],
    "Brand": ["Dell", "Logitech", "HP", "Samsung"],
    "Warranty_Years": [2, 1, 1, 3]
})

# Display them
df1

    Product  Price  Stock  Rating
0    Laptop  55000     10     4.5
1     Mouse    800     50     4.2
2  Keyboard   1500     30     4.4
3   Monitor  12000     15     4.6

In [19]:
pd.concat([df1,df2,df3], axis = 1) #for columns

,Product,Price,Stock,Rating,Product,Price,Stock,Rating,Category,Brand,Warranty_Years
0,Laptop,55000,10,4.5,Headphones,2500,25,4.3,Electronics,Dell,2
1,Mouse,800,50,4.2,Webcam,3500,18,4.1,Accessories,Logitech,1
2,Keyboard,1500,30,4.4,Printer,8500,8,4.0,Accessories,HP,1
3,Monitor,12000,15,4.6,Speaker,3000,20,4.4,Electronics,Samsung,3

## 2. Using `merge()` for SQL-Style Joins
- `merge()` is similar to SQL joins.
- Specify `on` or `left_on`/`right_on` to choose key columns.
- Join types: `inner` (default), `left`, `right`, `outer`.

In [20]:
import pandas as pd

sales_df = pd.DataFrame({
    "Order_ID": [101, 102, 103, 104, 105, 106, 107, 108],
    "Customer_ID": [1, 2, 3, 1, 4, 5, 2, 6],
    "Product_ID": [101, 102, 103, 101, 104, 105, 102, 106],
    "Quantity": [2, 1, 3, 1, 2, 4, 1, 2],
    "Sales": [110000, 800, 4500, 55000, 17000, 12000, 800, 6000]
})

sales_df

   Order_ID  Customer_ID  Product_ID  Quantity   Sales
0       101            1         101         2  110000
1       102            2         102         1     800
2       103            3         103         3    4500
3       104            1         101         1   55000
4       105            4         104         2   17000
5       106            5         105         4   12000
6       107            2         102         1     800
7       108            6         106         2    6000

In [ ]:
df1.columns

In [27]:
df1["Product_ID"] = [101, 102, 103, 104]

In [28]:
df1

    Product  Price  Stock  Rating  Product_ID
0    Laptop  55000     10     4.5         101
1     Mouse    800     50     4.2         102
2  Keyboard   1500     30     4.4         103
3   Monitor  12000     15     4.6         104

In [33]:
pd.merge(df1,sales_df, on="Product_ID" )

,Product,Price,Stock,Rating,Product_ID,Order_ID,Customer_ID,Quantity,Sales
0,Laptop,55000,10,4.5,101,101,1,2,110000
1,Laptop,55000,10,4.5,101,104,1,1,55000
2,Mouse,800,50,4.2,102,102,2,1,800
3,Mouse,800,50,4.2,102,107,2,1,800
4,Keyboard,1500,30,4.4,103,103,3,3,4500
5,Monitor,12000,15,4.6,104,105,4,2,17000

In [35]:
pd.merge(df1,sales_df, on="Product_ID", how = "right" )

,Product,Price,Stock,Rating,Product_ID,Order_ID,Customer_ID,Quantity,Sales
0,Laptop,55000.0,10.0,4.5,101,101,1,2,110000
1,Mouse,800.0,50.0,4.2,102,102,2,1,800
2,Keyboard,1500.0,30.0,4.4,103,103,3,3,4500
3,Laptop,55000.0,10.0,4.5,101,104,1,1,55000
4,Monitor,12000.0,15.0,4.6,104,105,4,2,17000
5,NaN,NaN,NaN,NaN,105,106,5,4,12000
6,Mouse,800.0,50.0,4.2,102,107,2,1,800
7,NaN,NaN,NaN,NaN,106,108,6,2,6000

In [29]:
print("df1:", df1.columns.tolist())
print("sales_df:", sales_df.columns.tolist())

df1: ['Product', 'Price', 'Stock', 'Rating', 'Product_ID']
sales_df: ['Order_ID', 'Customer_ID', 'Product_ID', 'Quantity', 'Sales']

In [36]:
pd.merge(df1,sales_df, on="Product_ID" , how = "left" )

,Product,Price,Stock,Rating,Product_ID,Order_ID,Customer_ID,Quantity,Sales
0,Laptop,55000,10,4.5,101,101,1,2,110000
1,Laptop,55000,10,4.5,101,104,1,1,55000
2,Mouse,800,50,4.2,102,102,2,1,800
3,Mouse,800,50,4.2,102,107,2,1,800
4,Keyboard,1500,30,4.4,103,103,3,3,4500
5,Monitor,12000,15,4.6,104,105,4,2,17000

In [37]:
pd.merge(df1,sales_df, on="Product_ID" , how = "outer" )

,Product,Price,Stock,Rating,Product_ID,Order_ID,Customer_ID,Quantity,Sales
0,Laptop,55000.0,10.0,4.5,101,101,1,2,110000
1,Laptop,55000.0,10.0,4.5,101,104,1,1,55000
2,Mouse,800.0,50.0,4.2,102,102,2,1,800
3,Mouse,800.0,50.0,4.2,102,107,2,1,800
4,Keyboard,1500.0,30.0,4.4,103,103,3,3,4500
5,Monitor,12000.0,15.0,4.6,104,105,4,2,17000
6,NaN,NaN,NaN,NaN,105,106,5,4,12000
7,NaN,NaN,NaN,NaN,106,108,6,2,6000

In [38]:
pd.merge(df1,sales_df, on="Product_ID" , how = "inner" )

,Product,Price,Stock,Rating,Product_ID,Order_ID,Customer_ID,Quantity,Sales
0,Laptop,55000,10,4.5,101,101,1,2,110000
1,Laptop,55000,10,4.5,101,104,1,1,55000
2,Mouse,800,50,4.2,102,102,2,1,800
3,Mouse,800,50,4.2,102,107,2,1,800
4,Keyboard,1500,30,4.4,103,103,3,3,4500
5,Monitor,12000,15,4.6,104,105,4,2,17000

## 3. Using `join()` with Index Alignment
- `join()` joins DataFrames on their index or on a key column.
- By default, joins on index; can specify `on='col'`.
- Useful for adding columns to an existing DataFrame.

## 4. Practical Examples
- Combine sales and revenue data to see performance.
- Merge students with marks to link records.
- Practice with realistic datasets to understand alignment and missing data handling.

## Mini Practice
1. Create three DataFrames: Products, Sales, and Revenue.
2. Concatenate them vertically and horizontally.
3. Merge Sales and Revenue using different join types.
4. Join Products with Sales based on index or a key.
5. Analyze missing values after joins.

In [ ]:

# 1. Create three DataFrames: Products, Sales, and Revenue

# 2. Concatenate them vertically and horizontally
# Write your code here

# 3. Merge Sales and Revenue using different join types (inner, left, right, outer)
# Write your code here

# 4. Join Products with Sales based on index or a key
# Write your code here

# 5. Analyze missing values after joins
# Use isna(), info(), or describe() to explore gaps
# Write your code here

---
## Summary
- Used `concat()` for stacking data vertically and horizontally.
- Performed SQL-style joins with `merge()`.
- Applied `join()` with index alignment.
- Explored practical use-cases like sales vs revenue, students vs marks.