# 🐼 Pandas - Class 5: Sorting & Basic Statistics
Welcome to **Class 5** of our Pandas series. Today we’ll learn how to sort data and calculate basic statistics.

## 1. Sorting Data
- Use `sort_values(by='col')` to sort by column values.
- Use `ascending=False` for descending order.
- Sort by multiple columns by passing a list.
- `sort_index()` sorts by row or column index.

In [1]:
import pandas as pd

data = {
    "Product": ["Laptop", "Mouse", "Keyboard", "Monitor", "Headphones",
                "Webcam", "Printer", "Tablet"],
    "Price": [55000, 800, 1500, 12000, 2500, 1800, 9000, 25000],
    "Stocks": [15, 50, 30, 12, 40, 25, 8, 20],
    "Rating": [4.5, 4.2, 4.6, 4.3, 4.1, 3.9, 4.0, 4.7]
}

df = pd.DataFrame(data)

df

      Product  Price  Stocks  Rating
0      Laptop  55000      15     4.5
1       Mouse    800      50     4.2
2    Keyboard   1500      30     4.6
3     Monitor  12000      12     4.3
4  Headphones   2500      40     4.1
5      Webcam   1800      25     3.9
6     Printer   9000       8     4.0
7      Tablet  25000      20     4.7

In [2]:
df.sort_values(by='Price')

      Product  Price  Stocks  Rating
1       Mouse    800      50     4.2
2    Keyboard   1500      30     4.6
5      Webcam   1800      25     3.9
4  Headphones   2500      40     4.1
6     Printer   9000       8     4.0
3     Monitor  12000      12     4.3
7      Tablet  25000      20     4.7
0      Laptop  55000      15     4.5

In [3]:
df.sort_values(by=['Price','Stocks'],ascending=[True,False])

      Product  Price  Stocks  Rating
1       Mouse    800      50     4.2
2    Keyboard   1500      30     4.6
5      Webcam   1800      25     3.9
4  Headphones   2500      40     4.1
6     Printer   9000       8     4.0
3     Monitor  12000      12     4.3
7      Tablet  25000      20     4.7
0      Laptop  55000      15     4.5

## 2. Descriptive Statistics
- `mean()`, `median()`, `mode()` for central tendency.
- `std()` for standard deviation.
- `describe()` for a summary of stats (count, mean, std, min, quartiles, max).

In [6]:
df.mean(numeric_only = True)

Price     13450.0000
Stocks       25.0000
Rating        4.2875
dtype: float64

In [7]:
df.median(numeric_only = True)

Price     5750.00
Stocks      22.50
Rating       4.25
dtype: float64

In [8]:
df.mode(numeric_only = True)

   Price  Stocks  Rating
0    800       8     3.9
1   1500      12     4.0
2   1800      15     4.1
3   2500      20     4.2
4   9000      25     4.3
5  12000      30     4.5
6  25000      40     4.6
7  55000      50     4.7

In [10]:
df.std(numeric_only=True)

Price     18670.679841
Stocks       14.432107
Rating        0.290012
dtype: float64

In [11]:
df.describe()

              Price     Stocks    Rating
count      8.000000   8.000000  8.000000
mean   13450.000000  25.000000  4.287500
std    18670.679841  14.432107  0.290012
min      800.000000   8.000000  3.900000
25%     1725.000000  14.250000  4.075000
50%     5750.000000  22.500000  4.250000
75%    15250.000000  32.500000  4.525000
max    55000.000000  50.000000  4.700000

## 3. Counting Values
- `value_counts()` shows the frequency of unique values in a Series.
- Use `normalize=True` to see percentages instead of counts.

In [14]:
df['Product'].value_counts(normalize = True)

Product
Laptop        0.125
Mouse         0.125
Keyboard      0.125
Monitor       0.125
Headphones    0.125
Webcam        0.125
Printer       0.125
Tablet        0.125
Name: proportion, dtype: float64

## 4. Correlation & Covariance
- `corr()` computes correlation between numeric columns.
- `cov()` computes covariance.
- Correlation values range from -1 (negative) to +1 (positive).

In [15]:
df.corr(numeric_only = True)

           Price    Stocks    Rating
Price   1.000000 -0.487223  0.495870
Stocks -0.487223  1.000000 -0.098981
Rating  0.495870 -0.098981  1.000000

In [16]:
df.cov(numeric_only = True)

               Price         Stocks       Rating
Price   3.485943e+08 -131285.714286  2685.000000
Stocks -1.312857e+05     208.285714    -0.414286
Rating  2.685000e+03      -0.414286     0.084107

In [17]:
df['Price'].corr(df['Rating'])

0.49586986724209386

## Mini Practice
1. Build a DataFrame with columns: Name, Age, Score, Height.
2. Sort the data by Score (descending).
3. Get mean, median, mode, and std of numeric columns.
4. Use value_counts on Name or any categorical column.
5. Compute corr() and cov() for all numeric columns.

In [ ]:
# Write your mini practice solution here

# 1. Build a DataFrame with columns: Name, Age, Score, Height

# 2. Sort the data by Score (descending)
# Write your code here

# 3. Get mean, median, mode, and std of numeric columns
# Write your code here

# 4. Use value_counts on Name or any categorical column
# Write your code here

# 5. Compute corr() and cov() for all numeric columns
# Write your code here

---
## Summary
- Learned to sort by columns with `sort_values` and by index with `sort_index`.
- Explored descriptive statistics: mean, median, mode, std, describe.
- Counted values with `value_counts`.
- Calculated correlation and covariance.